ungdev/UA-api

- .travis.yml
- README.md
- package.json
- prisma/schema.prisma
- seed.sql
- src/app.ts
- src/controllers/status.ts
- src/types.ts
- src/utils/database.ts
- src/utils/environment.ts
- src/utils/log.ts
- test/general.test.ts
- tests/auth.test.ts
- tests/general.test.ts
- tests/tournaments.test.ts
- yarn.lock
- Mise en place d'un dossier `tests`
- Mise à jour de Travis pour prendre en compte les tests
- L'organisation des fichiers suit les sections de l'open API (https://ua-api.uttnetgroup.fr/docs)
- Création des premiers tests d'intégrations pour les routes suivantes : 
- GET / (status de l'API)
- POST /contact (contacter le staff via un formulaire du front)
- GET /tournaments (récupérer la liste des tournois sans être identifié)
- POST /auth/register (création d'un utilisateur)
- POST /auth/validate/{token} (validation de l'enregistrement)
> Setup test

- src/controllers/index.ts
- src/controllers/tournaments/getTournaments.ts
- src/controllers/tournaments/index.ts
- src/operations/team.ts
- src/operations/tournament.ts
- src/types.ts
- tests/tournaments.test.ts
- Nouvelle route `GET /tournaments` qui retourne les tournois
- Création d'opérations réutilisable :
- `fetchTournaments` récupère l'ensemble des tournois
- `countTeamsWhere` compte les équipes selon une/des condition(s)
- Validation du test tournaments
> feat: GET /tournaments

- src/middlewares/settings.ts
- src/operations/settings.ts
- src/types.ts
-Midlleware : loginAllowed, shopAllowed
-Operation : settings.ts
-Errors : LoginNotAllowed, ShopNotAllowed
> Settings.ts

- src/scripts/discordSync.ts
- src/types.ts
- src/utils/discord.ts
- src/utils/toornament.ts
- Gère le scrypt toornacord pour les tournois solo (TFT, SSBU)
> Feat toornacord for solo team

- .github/pull_request_template.md
- uploads/.gitignore
- Supprime le dossier `uploads`
- Ajoute une section dans le template de la PR (visible quand merge sur master)
> Fix divers

- .env.example
- .eslintrc.json
- codecov.yml
- package.json
- src/app.ts
- src/scripts/discordSync.ts
- src/server.ts
- src/utils/environment.ts
- src/utils/sentry.ts
- tsconfig.json
- yarn.lock
- Ajoute Sentry sur l'API et les scripts
- Handle les exception à la racine du projet
Ajout de `SENTRY_URL`
> Add sentry

- codecov.yml
- Les checks codecov n'avaient pas été supprimés, cf PR #17, corrigé ici. 
nada
> Disable codecov checks

- .eslintrc.json
- src/middlewares/authentication.ts
- src/middlewares/user.ts
- src/utils/discord.ts
(j'aime les PR de 3 lignes)
En cours de review de la PR #18, j'ai remarqué qu'il y avait des async inutiles. Airbnb n'enforce pas par défaut de mettre un await dans une fonction asynchrone. La PR corrige cela.
Que dalle
> Add require await eslint rule in a async function

- package.json
- prisma/schema.prisma
- seed.sql
- src/controllers/index.ts
- src/controllers/partners/getPartners.ts
- src/controllers/partners/index.ts
- src/operations/partners.ts
- yarn.lock
- Ajout d'une table partners dans la base de données
- Ajout d'une route GET /partners
Aucune
> feat: add partners

- .eslintrc.json
- codecov.yml
- openapi.json
- openapi.yml
- package.json
- prisma/schema.prisma
- seed.sql
- src/app.ts
- src/controllers/index.ts
- src/controllers/partners/getPartners.ts
- src/controllers/partners/index.ts
- src/middlewares/authentication.ts
- src/middlewares/user.ts
- src/operations/partners.ts
- src/utils/discord.ts
- yarn.lock
- Ajout de la route GET /partners
- Mise à jour du fichier OpenAPI
- Fixes divers : supression des checks codecov sur les PR, enforce eslint, suppression de la route /uploads
Aucune
> add partners and some minor fixes

- prisma/schema.prisma
- seed.sql
- src/scripts/discordSync.ts
- src/utils/discord.ts
- simplifie la synchro discord
-
-
Exemple: DB_HOST -> DATABASE_HOST
-
-
-
> Remove staff role id

- package.json
- schema.prisma
- seed.sql
- src/scripts/discordReset.ts
- src/scripts/discordSync.ts
- src/types.ts
- src/utils/discord.ts
- src/utils/toornament.ts
- fix le script de synchronisation Toornament/Discord
- ajout d'améliorations
- ajoute un script permettant de supprimer tous les salons Discords créés par le script de synchro et de déassigner les rôles
Aucune
> Fix discord script

- src/utils/discord.ts
- Hotfix vers master pour corriger les pending discord sync jobs
- Dans le cas où il y a une erreur de réseau, rejette la promesse au lieu de laisser le programme tourner
> Add error catching on discord

- src/utils/validators.ts
- tests/auth/register.test.ts
> fix(dot-in-username): solved

- src/controllers/admin/scan/scan.ts
- src/controllers/teams/createTeam.ts
- src/controllers/teams/createTeamRequest.ts
- src/controllers/users/createCart.ts
- src/middlewares/validation.ts
- src/types.ts
- src/utils/validators.ts
- tests/admin/scan/scan.test.ts
- tests/admin/users/replace.test.ts
- tests/admin/users/updateUser.test.ts
- tests/auth/askResetPassword.test.ts
- tests/auth/login.test.ts
- tests/auth/register.test.ts
- tests/auth/resetPassword.test.ts
- tests/root/contact.test.ts
- tests/teams/createTeam.test.ts
- tests/teams/createTeamRequest.test.ts
- tests/teams/updateTeam.test.ts
- tests/users/createCart.test.ts
- tests/users/updateUser.test.ts
- Transformation de toutes les erreurs invalidBody qui renvoient maintenant l'élément invalide
- Ajout d'erreurs dans les types
- updates des tests
- mise a jour de la doc
> fix: explicited invalidbody

- docs/doc_api/concepts.md
- docs/doc_api/integration.md
- docs/doc_general/deadlines.md
- docs/doc_general/installation.md
Regarde dans les fichiers que j'ai modifiés, ils parlent d'eux même...
J'espère que c'est suffisamment détaillé sans trop l'être :)
> docs(api): added concepts.md

- src/controllers/admin/index.ts
- src/controllers/admin/logs/index.ts
- src/controllers/admin/logs/logs.ts
- src/controllers/admin/openapi.yml
- src/middlewares/log.ts
- src/operations/log.ts
- src/types.ts
- tests/admin/logs/logs.test.ts
- ajout de la route admin/logs
- ajout des tests correspondants
(- fix de syntaxe sur une erreur)
> feat(logs): admins can now see logs

- package.json
- src/scripts/sendDiscordMails.ts
Le contenu du mail n'est **pas** présent (mais ça devrait marcher)
> feat: script to inform users about the discord server

- schema.prisma
- src/controllers/admin/users/getCarts.ts
- src/controllers/items/getItems.ts
- src/controllers/openapi.yml
- src/controllers/users/createCart.ts
- src/operations/carts.ts
- src/operations/item.ts
- src/types.ts
- src/utils/carts.ts
- src/utils/filters.ts
- src/utils/helpers.ts
- tests/admin/carts/refund.test.ts
- tests/admin/users/getCarts.test.ts
- tests/etupay/callback.test.ts
- tests/services/email.test.ts
- tests/tickets/getTicket.test.ts
- tests/users/createCart.test.ts
- tests/users/getCarts.test.ts
- tests/utils.ts
- tests/utils/pdf.test.ts
The `CartItem`s now include these 3 new properties :
- `price: Int` the full price of the item when it was sold
- `reducedPrice: Int?` the reduced price of the item when bought *(this is the real price paid by the user)*
- `forcePaid: Boolean` indicated whether the item was bought directly on the website or via another way (so the user has been marked as paid by an admin). _This can be used by the treasurer if needed._
- Added a check so only people on the same team can pay each others tickets
- Added a new error for users not in the same team
- Added an applyPartnerDiscount utils function
- Changed the way fetchUserItems works : `/items` now returns `reducedPrice`s when applicable
* Updated the openapi documentation accordingly
* Updated the tests to work with the newly created fields
* …
> refactor(carts): changed the way carts pricing work

- src/controllers/teams/getIndividualTeam.ts
- src/controllers/teams/index.ts
- src/controllers/teams/openapi.yml
- tests/teams/getIndividualTeam.test.ts
Adding Individual Team Route needed for the front
> feat: add individual team route

- seed.sql
- src/controllers/teams/createTeam.ts
- src/controllers/teams/createTeamRequest.ts
- src/operations/user.ts
- src/types.ts
- tests/teams/createTeam.test.ts
- tests/teams/createTeamRequest.test.ts
* update discount count for ssbu
> fix: users cannot join tournaments where ticket price is not the same as previously bought ticket

- src/controllers/users/createCart.ts
- src/operations/item.ts
- src/types.ts
- tests/items/getItems.test.ts
- tests/users/createCart.test.ts
It's missing the tests, but idk how to do them, so i didn't do them :)
> fix: ssbu discount is not sent anymore when the user already paid for it

- schema.prisma
- src/controllers/admin/index.ts
- src/controllers/admin/openapi.yml
- src/controllers/admin/repo/depositRepoItem.ts
- src/controllers/admin/repo/getRepoItems.ts
- src/controllers/admin/repo/getRepoLogs.ts
- src/controllers/admin/repo/index.ts
- src/controllers/admin/repo/removeRepoItem.ts
- src/controllers/users/createCart.ts
- src/operations/repo.ts
- src/types.ts
- src/utils/responses.ts
- tests/admin/repo/depositRepoItem.test.ts
- tests/admin/repo/getRepo.test.ts
- tests/admin/repo/getRepoLogs.test.ts
- tests/admin/repo/removeRepoItem.test.ts
- tests/setup.ts
**DB :**
```RepoLogs : id, itemId, action, timestamp, userId```
```RepoItems : id, type, forUserId, zone?```
**Routes :**
```GET /api/repo/user?id={base64(encrypted_user_id)}```
Retourne les infos de base du joueur + les items actuellement déposés :
```graph
{
firstname,
lastname,
place,
id,
repoItems: [{
type,
id,
zone
}]
}
```
:warning: Doit fail si l'utilisateur n'a pas été scanné (scannedAt IS NULL) ou s'il n'a pas été lock (lockedAt IS NULL) et que ce n'est pas un orga
```POST /api/repo/user/{userId}/items```
Permet de notifier le dépôt d'un item. Paramètres :
```graph
{
items: [{
type,
zone
}]
}
```
Retourne une `201 Created`
:warning: Doit fail si l'utilisateur n'a pas été scanné (scannedAt IS NULL) ou s'il n'a pas été lock (lockedAt IS NULL) et que ce n'est pas un orga
```DELETE …
```
> Ajout du dépôt de matériel

- package.json
- pnpm-lock.yaml
simply added a dependency, nothing more
> build: added the ts-node module as a dev dependency

- schema.prisma
- src/controllers/admin/emails/send.ts
- src/controllers/admin/tournaments/updateTournament.ts
- src/controllers/admin/users/getUsers.ts
- src/controllers/teams/createTeam.ts
- src/controllers/teams/getTeams.ts
- src/operations/caster.ts
- src/operations/team.ts
- src/operations/tournament.ts
- src/types.ts
- src/utils/discord.ts
- src/utils/validators.ts
- tests/admin/emails/send.test.ts
- tests/admin/logs/logs.test.ts
- tests/admin/users/getUsers.test.ts
- tests/teams/createTeam.test.ts
- tests/teams/getTeams.test.ts
- tests/utils.ts
- tests/utils/pdf.test.ts
Changement du type `TournamentId` en `string`
Tout ce qui touche au type `TournamentId`
> refactor: removed TournamentId enum

- seed.sql
player counts in seed.sql
none
> fix: player count per tournament

- seed.sql
- src/middlewares/settings.ts
- src/types.ts
- src/utils/login.ts
- tests/admin/auth/login.test.ts
- tests/admin/emails/send.test.ts
- tests/discord/syncRoles.test.ts
- tests/teams/createTeam.test.ts
- tests/utils/pdf.test.ts
> fix: login

- src/middlewares/settings.ts
> Feat: Allow early login for admin

- schema.prisma
- src/controllers/admin/items/index.ts
- src/controllers/admin/items/updateItem.ts
- src/controllers/openapi.yml
- src/controllers/users/createCart.ts
- src/operations/item.ts
- src/types.ts
- src/utils/filters.ts
- tests/admin/items/getItem.test.ts
- tests/admin/items/updateItem.test.ts
- tests/utils.ts
Added a way to add an availability period for items in the shop
> feat: item availability, checks at cart creation

- src/operations/team.ts
> fix: lock teams bugs

- src/operations/carts.ts
- src/operations/team.ts
> Fix: Make discord working with new lock system

- schema.prisma
- src/operations/team.ts
- src/services/discord.ts
- src/utils/discord.ts
> feat: channels are now deleted when a team is unlocked

- schema.prisma
- src/operations/team.ts
- src/services/discord.ts
- src/utils/discord.ts
* feat: channels are now deleted when a team is unlocked
* fix: basically lint
* fix: wait wtf ?
---------
> feat: channels are now deleted when a team is unlocked (#173)

- src/controllers/openapi.yml
- src/controllers/partners/getPartners.ts
- src/utils/filters.ts
- tests/partners/getPartners.test.ts
- tests/tournaments/getTournaments.test.ts
> small change in tournament and partners positions

- src/controllers/users/createCart.ts
- src/operations/user.ts
Only checking items in the cart now
> fix: when ONE item was not available, no item was

- .env.test.example
- .eslintrc.json
- .gitignore
- README.md
- package.json
- pnpm-lock.yaml
- src/services/database.ts
- src/utils/env.ts
- tests/middlewares.test.ts
- tests/setup.ts
- tests/utils/env.test.ts
* a new file .env.test is loaded when process.env.NODE_ENV is 'test'
* 2 new commands in pnpm : schema:push and test:schema:push
There shouldn't be. Hopefully
> feat: there is now a proper test environment

- schema.prisma
> fix: schema prisma

- schema.prisma
- src/scripts/mails/index.ts
- src/scripts/mails/notpaid.ts
- src/services/email/serializer.ts
- src/utils/validators.ts
> Feat mails

- schema.prisma
- src/operations/upload.ts
- tests/upload.ts
> fix: file upload

- src/controllers/teams/createTeamRequest.ts
> fix: team request

- src/controllers/teams/createTeamRequest.ts
> fix: request team

- src/utils/discord.ts
> fix: discord logs

- src/operations/upload.ts
- tests/admin/upload/deleteFile.test.ts
- tests/upload.ts
> feat: add images to webp

- .env.example
- .env.test.example
- src/services/email/index.ts
- src/utils/env.ts
- tests/admin/users/updateTrombi.test.ts
> Add gmail smtp support and fix badges

- .env.example
- schema.prisma
- src/operations/user.ts
- src/scripts/mails/index.ts
- src/scripts/mails/tickets.ts
- src/utils/env.ts
> fix(mails): update mails for ua23

- codecov.yml
- src/controllers/admin/users/updateUser.ts
- src/operations/user.ts
- src/scripts/mails/index.ts
- src/types.ts
- tests/admin/users/updateUser.test.ts
> Fix mails and small issues

- src/controllers/admin/badges/generateBadges.ts
- src/utils/badge.ts
> Badges recto verso

- src/controllers/users/getOrgas.ts
- src/controllers/users/openapi.yml
- tests/users/getOrgas.test.ts
* added query parameter includeVieux to tell whether to return the vieux commission
> fix: route GET /users/orgas was not working

- src/controllers/admin/openapi.yml
- src/operations/user.ts
- tests/admin/users/updateTrombi.test.ts
* fix: typo, wupsy
* fix: the typo was present in more places than expected
> Fix/typo (#221)

- LICENSE
- src/controllers/admin/repo/depositRepoItem.ts
- src/operations/repo.ts
- src/types.ts
- tests/admin/repo/depositRepoItem.test.ts
- tests/admin/repo/getRepo.test.ts
- tests/admin/repo/getRepoLogs.test.ts
> Feat: better Repo

- src/services/email/serializer.ts
> fix: better emails

- src/utils/validators.ts
> fix: allowed # in team name regex

- src/types.ts
- src/utils/validators.ts
> Merge master

- src/controllers/admin/users/getUsers.ts
- src/operations/user.ts
- src/types.ts
> feat: create majority filter

- src/controllers/teams/getIndividualTeam.ts
- src/utils/filters.ts
> fix: plus d'info sensible quand on cherche /api/teams/:teamID (normalement)

- src/operations/user.ts
feat: the big search can now handle users id
> feat: the big search can now handle users id

- src/operations/user.ts
> feat: discordID in superSearch

- src/controllers/admin/badges/generateBadges.ts
> fix: singe badge include firstaid logo

- .github/workflows/ci.yml
> Merge dev in master
